apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: aoub4x8xx-python 
  janus-idp.io/tekton: aoub4x8xx-python
  backstage.io/kubernetes-id: aoub4x8xx-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: aoub4x8xx-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml