apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: aoub4x8xx-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: aoub4x8xx-python 
  name: aoub4x8xx-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: aoub4x8xx-python 
